#!/usr/bin/env bash
# Build a pre-baked aarch64 GitHub Actions runner guest image.
#
# Boots lima/runner-aarch64.yaml once (so the runner + git/node + gha-run-once
# provision), cleans the result for reuse, snapshots its disk to a compact
# qcow2, and emits a Lima template that boots that image with NO per-job
# provisioning. Point the consumer's LIMA_TEMPLATE at the emitted template to
# cut VM startup from minutes to ~20s.
#
# Requirements: limactl and nix (used for qemu-img; the host has no qemu). No
# host sudo — image cleaning uses the guest's passwordless sudo. Run when the
# host is otherwise idle: it boots a 4-vCPU / 12 GiB VM, which would contend
# with live job VMs.
#
# Re-run whenever the runner version or the provisioning in runner-aarch64.yaml
# changes. Output defaults outside the repo (override with OUTDIR).
set -euo pipefail

dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
src_template="${SRC_TEMPLATE:-$dir/runner-aarch64.yaml}"
outdir="${OUTDIR:-$HOME/.local/share/gha-images}"
vm="gha-imgbuild-$$"

command -v limactl >/dev/null || { echo "error: limactl not found on PATH" >&2; exit 1; }
[ -f "$src_template" ] || { echo "error: source template $src_template not found" >&2; exit 1; }
mkdir -p "$outdir"
# Resolve to an absolute path so the emitted file:// image URL and the printed
# LIMA_TEMPLATE work regardless of cwd (OUTDIR may be given as a relative path).
outdir=$(cd "$outdir" && pwd)
# Version the artifacts so a re-run never overwrites the image that a previously
# generated template — possibly still staged by the running consumer — points
# at (a clobbered image fails Lima's digest check until the daemon restarts).
# Switching LIMA_TEMPLATE to the new file is then a clean cutover.
ts=$(date +%Y%m%d-%H%M%S)
img="$outdir/runner-aarch64-prebuilt-$ts.qcow2"
tmpl="$outdir/runner-aarch64-prebuilt-$ts.yaml"

cleanup() { limactl delete --force "$vm" >/dev/null 2>&1 || true; }
trap cleanup EXIT

echo ">> Booting $vm from $src_template (provisions runner + tools)..."
limactl start --tty=false --name "$vm" "$src_template"

echo ">> Sanity-checking the provisioned guest..."
limactl shell "$vm" -- sh -c \
  'command -v gha-run-once >/dev/null && sudo test -x /home/runner/actions-runner/run.sh' \
  || { echo "error: guest is missing gha-run-once or the runner" >&2; exit 1; }

echo ">> Cleaning the image for reuse (reset cloud-init so Lima re-bootstraps"
echo "   clones; drop host keys/machine-id; clear runner work + apt cache)..."
limactl shell "$vm" -- sudo bash -c '
  set -e
  cloud-init clean --logs
  rm -f /etc/ssh/ssh_host_*
  truncate -s 0 /etc/machine-id
  rm -rf /home/runner/actions-runner/_work /home/runner/actions-runner/_diag /home/runner/.cache
  apt-get clean
  rm -rf /var/lib/apt/lists/*
'

echo ">> Stopping $vm..."
limactl stop "$vm"

# vz stores a single raw disk under the instance dir; ask limactl where it is
# (so a custom LIMA_HOME is respected) and flatten it into a compact qcow2 via
# the nix-provided qemu-img. Write to a temp then rename so a failure can't
# leave a half-written image in place.
instdir=$(limactl list "$vm" --format '{{.Dir}}')
[ -n "$instdir" ] && [ -f "$instdir/disk" ] || {
  echo "error: could not locate the disk for $vm" >&2; exit 1; }
echo ">> Flattening $instdir/disk -> $img ..."
nix shell nixpkgs#qemu -c qemu-img convert -f raw -O qcow2 "$instdir/disk" "$img.tmp"
mv -f "$img.tmp" "$img"

digest="sha256:$(shasum -a 256 "$img" | awk '{print $1}')"
echo ">> Image digest: $digest"

echo ">> Writing template $tmpl ..."
# cpus/memory/disk/user/mounts mirror runner-aarch64.yaml; keep them in sync if
# that template changes.
cat > "$tmpl" <<EOF
# Pre-baked aarch64 GitHub Actions runner guest.
# Generated by lima/build-prebuilt-image.sh from runner-aarch64.yaml.
# Boots with NO per-job provisioning. Host-specific (absolute path + digest) —
# regenerate with the script rather than editing by hand.
vmType: vz
arch: aarch64
images:
  - location: "file://$img"
    arch: aarch64
    digest: "$digest"
cpus: 4
memory: "12GiB"
disk: "40GiB"
user:
  name: lima
mounts: []
EOF
# The consumer rejects a group/world-writable LIMA_TEMPLATE; force a safe mode
# regardless of the operator's umask.
chmod 0644 "$tmpl"

echo ""
echo "Done. Point the consumer at the pre-baked image with:"
echo "    LIMA_TEMPLATE=$tmpl"
echo "Restart the consumer with that env when it is idle."
echo "Older runner-aarch64-prebuilt-*.{qcow2,yaml} in $outdir can be deleted"
echo "once no consumer references them."
