#!/bin/sh
# Launch the aarch64-linux remote builder (nixpkgs' darwin.linux-builder),
# invoked by the LaunchAgent that install-launchd.sh installs.
#
# All builder runtime state lives under one self-contained dir ($BASE):
#   nixos.qcow2         persistent builder store (drive1; mutable, NOT in repo)
#   keys/               guest host keypair (private key; NOT in repo)
#   run-builder-gcroot  gcroot pinning the known-good run-builder closure
#   run/                ephemeral TMPDIR (store.img + 9p certs/xchg shares)
#   builder.log         stdout+stderr (see the plist)
#
# Two non-obvious invariants this wrapper enforces (the reason it exists rather
# than calling `nix run nixpkgs#darwin.linux-builder` directly):
#
#  1. STABLE TMPDIR (off /tmp). darwin.linux-builder 9p-mounts the host's CA
#     bundle into the guest at /etc/ssl/certs from a dir under $TMPDIR. The
#     default /tmp gets reaped by macOS on a multi-day VM, emptying the share
#     and breaking TLS to cache.nixos.org (curl error 77). run-nixos-vm keeps
#     our TMPDIR only when BOTH USE_TMPDIR and TMPDIR are non-empty.
#
#  2. PINNED qemu. We launch the run-builder resolved via the gcroot symlink,
#     NOT `nix run nixpkgs#...` — the registry nixpkgs can drift to a qemu that
#     aborts on Apple-Silicon HVF (hvf_arch_init_vcpu: HV_SYS_REG_SMCR_EL1
#     assertion -> Abort trap: 6). To intentionally bump the builder later,
#     repoint the gcroot:
#       nix-store --realise <new-run-builder> --indirect --add-root "$GCROOT"
set -eu

BASE="${GHA_BUILDER_HOME:-$HOME/.local/share/gha-linux-builder}"
GCROOT="$BASE/run-builder-gcroot"   # -> pinned /nix/store/...-run-builder

export NIX_DISK_IMAGE="${NIX_DISK_IMAGE:-$BASE/nixos.qcow2}"   # warm persistent store (drive1)
export KEYS="${KEYS:-$BASE/keys}"                              # host keypair -> keeps known_hosts valid
export NIX_SSL_CERT_FILE="${NIX_SSL_CERT_FILE:-/nix/var/nix/profiles/default/etc/ssl/certs/ca-bundle.crt}"
export USE_TMPDIR=1                                            # both required, or run-nixos-vm reverts to /tmp
export TMPDIR="$BASE/run"

# Fresh runtime dir each start: store.img (ephemeral erofs base) and the
# certs/xchg 9p shares are all regenerated by run-nixos-vm.
rm -rf "$TMPDIR"
mkdir -p "$TMPDIR"

runbuilder="$GCROOT/bin/run-builder"
if [ ! -x "$runbuilder" ]; then
  echo "start-builder: $runbuilder missing/not executable (gcroot broken? run nix-store --realise <run-builder> --indirect --add-root $GCROOT)" >&2
  exit 1
fi

echo "start-builder: launching $(readlink "$GCROOT") with TMPDIR=$TMPDIR NIX_DISK_IMAGE=$NIX_DISK_IMAGE KEYS=$KEYS"
exec "$runbuilder"
